DataManagementLab/bp-tool

bp/templates/bp/index.html
bp/templates/bp/project_overview.html
bp/urls.py
bp/views.py

Ungraded projects are listed under `project/ungraded`.
The filter is implemented like the ones for the logs (attention and unread).

Ungraded projects can be filtered

---

bp/templates/bp/index.html

Fixed some pluralization issues and added spacing between buttons if they are on different lines.

Various fixes in index.html

---

bptool/lti/urls.py

We will add more urls regarding lti, so move them into own directory

Move lti urls into own file

---

bp/admin.py

Fix import

---

bptool/lti/urls.py
bptool/lti/views.py

Connects accounts with preloaded student models based on email
Solves #20 
Probably noteworthy that I did not install a moodle server for this, so testing on my part is certainly not complete.
Still, based on available testing, I have no reason to believe that it doesn't work as intended.

Connect students with respective model

---

bp/roles.py
bp/timetracking/views.py

The different roles of TL, student and Orga need to be managed. Doing that in a dedicated place improves maintainability
Future additions shall be made in roles.py

Consolidate role management

---

bp/index/urls.py
bp/index/views.py
bp/templates/bp/index/index_student.html
bp/templates/bp/index/index_tl.html

Depends on #45 #46 #47 
Closes #33

Overview page for tls and students

---

bp/models.py
bp/templates/bp/timetracking/render_timetracking.html
bp/templates/bp/timetracking/render_timetracking_overview.html
bp/templates/bp/timetracking/timetracking_interval_detail.html
bp/templates/bp/timetracking/timetracking_overview.html
bp/templates/bp/timetracking/timetracking_project_overview.html
bp/timetracking/views.py

Gesamtstunden Zeiterfassung

---

bp/templates/bp/control_navbar.html

TLs have the tt and the logs
Students only have tt, but might get more later

TL and student navbar

---

bp/timetracking/forms.py

Fields for start and end are actual date fields now
Fixed issues in relation to invalid dates
Part of #57

Improve interval forms

---

bp/templates/bp/timetracking/render_timetracking.html
bp/templates/bp/timetracking/render_timetracking_overview.html

Not much of a difference tbh
Part of #57

Totals are bold now

---

bp/templates/bp/timetracking/timetracking_overview.html
bp/timetracking/views.py

Overview is now TL-only; students have the tt project overview
Removed timetable and added button to get to project overview for TLs
Part of #57

Timetracking overview changed

---

bp/forms.py
bp/grading/ag/forms.py
bp/grading/ag/views.py
bp/grading/urls.py
bp/urls.py
bp/views.py

grading should be in its own module
Also improved AG grading form with better error checking and user-friendlier website

Move grading logic into own module

---

bp/templates/bp/project_info_tabs.html
bp/templates/bp/render_gradings_tab.html

Put the gradings, orgalogs and tl logs into tabs for better visualization
Depends on #64

Improve project info misc

---

bp/templates/bp/project_info_misc_grading_content.html
bp/templates/bp/project_info_misc_grading_desc.html
bp/templates/bp/project_info_misc_log_content.html
bp/templates/bp/project_info_misc_log_desc.html
bp/templates/bp/project_info_misc_orgalog_content.html
bp/templates/bp/project_info_misc_orgalog_desc.html
bp/templates/bp/project_info_table.html
bp/templates/bp/project_info_tabs.html
bp/templatetags/tags_bp.py
bp/templatetags/tags_project_info_misc.py
bp/templatetags/tags_project_info_table.py

Similar to #65 
Prepares the code for the next stage of decoupling by creating tags for each tab (description and content)
Depends on #67

Improve project info misc separate

---

bp/tllogs/urls.py
bp/urls.py

Move tl log urls into own directory

---

bp/templates/bp/timetracking/timetracking_project_overview.html
bp/timetracking/models.py
bp/timetracking/views.py

The hours are normalized against the number of days in the interval
Closes #49

Add chart displaying hours spent per interval

---

bp/index/views.py

Make all objects on the orga index page dependent on the same chosen BP to avoid potential mixups and to make it easier to reason about them

Improve orga index view

---

bp/admin.py

In December, I saw that you implemented random group assignments.
The initial implementation, while fulfilling its requirements, wasn't very readable in my eyes, so I created this implementation which hopefully you too will consider more readable.
The improved implementation works like this:
1. Get all groups
2. Randomly shuffle the groups
3. Split them into virtual peer groups that only exist in the local scope
4. Check that each peer group conforms to the constrains
5. If not, go back to 2, else proceed
6. Create the real peer groups and store them in the database
The proof of constraint satisfaction and uniform random assignments is trivial.
Large parts of the initial implementation have been reused to ensure similar external behaviour. The most significant difference is the …

Make assignment of peer groups more readable

---

bp/forms.py
bp/grading/ag/views.py
bp/grading/orga/forms.py
bp/grading/orga/views.py
bp/models.py
bp/static/bp/css/custom.css
bp/templates/bp/grading/orga/grades_import.html
bp/templates/bp/project/projects_import.html
bp/templates/bp/students_import.html
bp/views.py

- added explanation of import files
- Import: several exceptions are now caught and get passed to the user (column missing, project doesn't exist, invalid entry, entry already exists)
- Teilnehmer Import: if student already exists he/she won't get added (if moodle id is the same)

Improve import

---

bp/grading/orga/forms.py
bp/grading/orga/views.py
bp/templates/bp/grading/orga/grades_import.html

- It's now possible to upload a CSV file with both, pitch and documentation grade
- adjusted helping text for grade upload accordingly

Upload for pitch and documentation grade in one file

---

bp/admin.py
bp/models.py
bp/static/bp/css/custom.css
bp/templates/bp/tl.html
bp/templates/bp/tl_overview.html
bp/templates/bp/tllogs/orga/log.html
bp/templates/bp/tllogs/orga/log_overview.html
bp/tllogs/api/views.py
bp/tllogs/models.py
bp/tllogs/orga/views.py
bp/tllogs/urls.py
bp/views.py

- replaced good/bad rating of logs by a star rating (1-5 stars)

Tl log star evaluation

---

bp/models.py
bp/templates/bp/index/index.html
bp/templates/bp/project/project_overview.html
bp/templates/bp/timetracking/statistics_orga.html
bp/templates/bp/timetracking/statistics_tl.html
bp/templates/bp/timetracking/timetracking_project_overview.html
bp/timetracking/urls.py
bp/timetracking/views.py
bp/urls.py

- added graphs for time group spent comparison showing to TLs and Orga
- for total time spent
- for every category

Time measurement statistics
